
services:
  mysql:
    image: mysql:8.0
    container_name: marspy-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Aa01010101;
      MYSQL_DATABASE: marspy
      MYSQL_USER: marspy
      MYSQL_PASSWORD: MarsPy0101;
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: marspy-backend
    restart: unless-stopped
    environment:
      PORT: 3001
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: marspy
      DB_USER: marspy
      DB_PASSWORD: MarsPy0101;
      JWT_SECRET: k9Wq3mX7vL2nR8pT5hY1cZ6jA0bN4sD+
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_MODEL: ${GEMINI_MODEL}
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend/assets:/app/assets

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: marspy-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data:
